export default {
    EN: {
        main: {
            what: "what is that?",
            desc: "Attention! Cases are issued according to the amount of deposits. The amount of deposits is calculated from 02:00 to 02:00 the following night. If you don't have time to open your free case before 02:00, the progress burns out..",
            pay: "You have topped up your balance by",
        },
        navElem: {
            users: "Users",
            cases: "Cases",
            upgrade: "Upgrades",
            contracts: "Contracts",
            online: "Online",
        },
        header: {
            cases: "Cases",
            upgrade: "Upgrade",
            contracts: "Contracts",
            deposit: "Deposit",
            bonuses: "Bonuses",
            wheel: "Wheel",
            knifeGame: "Guess the knife",
        },
        subheader: {
            missions: "Missions",
            calendar: "Calendar",
            cooperation: "Cooperation",
            referral: "Referral System",
            faq: "FAQ",
            freeCase: "Free Case",
        },
        login: {
            title: "Login",
            title1: "I agree with the",
            title2: "Terms of Service",
            title3: "Privacy Policy",
            title4: "and Cardholder Agreement",
            subtitle: "I am at least 18 years old",
            apply: "Apply",
        },
        profile: {
            profileTop: {
                deposit: "Deposit",
                tradeUrl: "Trade-URL",
                howWork: "How does it work?",
                promocode: "Promocode",
                promocodeText: "Do you have a gift code?",
                enterPromocode: "Enter promo code",
                bestCase: {
                    title: "Best Case",
                    subtitle: "Empty",
                    open: "Open case",
                },
                bestDrop: {
                    title: "Best Drop",
                    subtitle: "Empty",
                },
            },
            profileBottom: {
                skins: "Items",
                upgrade: "Upgrades",
                contracts: "Contracts",
                stock: "In Stock",
                sell: "Sell All",
            },
        },
        missions: {
            header: "Missions",
        },
        calendar: {
            top: {
                text: "Open the calendar boxes daily and get a reward! Every 10th day there is a SUPERPRISE waiting for you!",
                rules: "Calendar rules",
            },
            title: "Calendar Prizes",
            bottom: {
                bonus: "Balance",
                balance: "Bonus",
                key: "Case",
                case: "Key",
                random: "Random",
                item: "Skin",
                promo: "Promo code",
            },
        },
        upgrade: {
            header: "Upgrade",
            info: "The chance of a",
            chance: "successful upgrade",
            yourItems: "Your items",
            siteItems: "Upgrade items",
            price: "Price",
            all: "All",
            contraband: "Contraband",
            covert: "Covert",
            classified: "Classified",
            restricted: "Restricted",
            milspec: "Mil-spec",
            industrial: "Industrial",
            consumer: "Consumer",
            price: "Price",
        },
        deposit: {
            wallet: "Wallet",
            title: "Deposit",
            method: "Selected payment method",
            amount: "Amount",
            promocode: "Promocode",
            order: "Deposit",
            not_selected: "Not Selected",
        },
        trade: {
            url: "Trade-URL",
            desc: "Trade URL is a link that gives you the opportunity to trade with players who are not on your friends list",
            link: "Link",
            where: "Where to get?",
            enterLink: "Enter your link",
            apply: "Apply",
        },
        promocode: {
            title: "Promocode",
            desc: "Look for codes in our social networks and newsletters, enter in the field below and get money for balance or cases",
            apply: "Apply",
        },
        freecase: {
            header: "Free Cases",
            title: "OPEN FREE CS2 CASES EVERY DAY",
            desc: "To open a daily case, you need reach the required level by earning XP.The higher your level, the more cases are available to you",
            desc2: "For example, at level 20, you can open three cases every day. In order not to forget to pick up a daily case every day, subscribe to notifications. We will remind you of uncollected cases",
            open: "OPEN CASE",
            lock: "LOCK",
            free: "FREE",
        },
        socialModals: {
            title: "ONE-TIME BONUS",
            desc: "To receive a One-time bonus, you must:",
            condition: "Subscribe to",
            important: "IMPORTANT:",
            desc2: "The screenshot should be full-screen and clear. Any attempt to cheat will result in the rejection of the prize and the task being blocked without the possibility of appeal..",
        },
        replaceItem: {
            title: "Skin Replacement",
            return: "We will return it to the balance",
            desc: "Choose a skin",
            replace: "Replace",
            cancel: "Cancel",
        },
        raffleHour: {
            header: "Raffle",
            title: "Every hour",
            dep: "When replenishing from:",
            time: "Time left",
            participate: "Participate",
            winners: "Latest winners",
            show: "Show more",
            day: "Days",
            hour: "Hours",
            min: "minutes",
            sec: "Seconds",
        },
        raffleDay: {
            title: "Every day",
        },
        raffleWeek: {
            title: "Every week",
        },
        bonuses: {
            title: "Gift",
            ot: "from",
            text: "You are already with us",
            text1: "day",
            text2: "thank you for choosing us!",
            item: "Bonus cases",
            itemDesc: "Open a case monthly!",
            item1: "Daily bonuses",
            item1Desc: "Claim your reward every day!",
            bonus: "One-time bonuses",
            subscribe: "Subscribe to",
            to: "our",
            you_bonus: "Your bonus",
            take: "Take",
        },
        wheel: {
            title: "Wheel",
            subTitle: "Bonus",
            hours: "Hours",
            minutes: "Minutes",
            seconds: "Seconds",
            spin: "Spin...",
            open: "Spin",
            promo: "Your promo code (click to copy):",
            use: "Use",
            refresh: "Spin some more",
            what: "what might fall out?",
            free: "Until free",
            open1: "openings left:",
        },
        knifeGame: {
            header: "Guess where the knife",
            balance: "Balance",
            knivesCount: "Number of knives",
            betAmount: "Bet amount",
            multiplier: "Multiplier",
            startGame: "Start game",
            currentMultiplier: "Current multiplier",
            potentialWin: "Potential win",
            youWin: "You won!",
            youLose: "Knife! You lost",
            history: "Game history",
            topWins: "Top wins",
            noHistory: "No games yet",
            noTopWins: "No wins yet",
            howToPlay: "How to play?",
            howDesc1: "Choose the number of knives (1, 2 or 3), enter the bet and click Start.",
            howDesc2: "Click on the cells to reveal them. Avoid knives! Each safe cell increases your multiplier.",
            howDesc3: "You can cash out at 1/2, x2 or x3, or risk it all for maximum payout.",
            loginRequired: "Please log in to play",
        },
        referral: {
            title: "Referral system",
            silver: "Silver",
            gold: "Gold",
            platinum: "Platinum",
            promocode: "Promocode",
            create: "Create",
            discount: "Discount",
            percent: "Your percent",
            limit: "Limit",
            total_deposit: "Deposit up by",
            gain: "Your earnings",
            dep: "When replenishing from",
            copy: "Copy",
        },
        contracts: {
            title: "Contracts",
            contract: "Contract",
            create: "Create a contract",
            add: "Add the minimum",
            item: "items",
            available: "Items available for contract",
            happy: "Congratulations!",
            refresh: "Start again",
            sell: "Sell ​​for",
            warning: "There are no items for the contract!",
            warning2: "Open several cases",
            warning3:
                "return to this page and you will be able to create a contract!",
        },
        faq: {
            title: "FAQ",
            item: "I topped up my balance, but the money didn't arrive. What should I do?",
            desc: "If the funds do not arrive immediately after replenishment, do not worry. Wait 1 hour. If the money has not arrived within an hour, please contact support, indicating the payment details.",
            item1: "After opening the case, the item has not arrived or you cannot pick it up. What should you do?",
            desc1: "If the item has not arrived, go to your profile and click on the “Claim” link on the item you are interested in. If the item is not displayed, it may be that: your exchange is blocked, your inventory is hidden, the bot has problems with the Steam connection. Please write to our support and we will find the reason and solve it as quickly as possible.",
            item2: "I have money on my Steam account, but it is not displayed on caseblaze. Why?",
            desc2: "Unfortunately, the Steam balance does not work on caseblaze. But you can always top up your balance separately, via the “Deposit” button",
            item3: "Why can't I apply a promo code?",
            desc3: "Some promo codes can only be used at a certain Steam account level. Unfortunately, you cannot use a promo code with a Steam account level 0.",
            item4: "I didn't find the question I was interested in.",
            desc4: "Don't be upset. You can always write to us in support and we will answer your question as quickly as possible.",
        },
        cases: {
            content: "Contents of the case",
            sign: "Sign in with Steam",
            warning: "Steam authorization is required to open cases",
            enough: "not enough",
            deposit: "Deposit",
            open: "Open for",
            free: {
                title: "TO OPEN A CASE YOU NEED",
                text: "Top up your balance in the last 24 hours by at least",
                text1: "In the last 24 hours you have replenished your balance by",
                text2: "Important! Hurry to open before 02:00,",
                text3: "otherwise the progress of replenishments will be reset",
            },
            return: "again",
            sell: "Sell ​​for",
            sellAll: "Sell ​​everything for",
            upgrade: "in upgrade",
        },
        contacts: {
            help: "Need help?",
            questions:
                "For any questions and suggestions, write to us at the e-mail —",
        },
        cooperation: {
            name: "Cooperation",
            title: "Boost your income with caseblaze — direct advertiser of gambling products",
            desc: "High conversion, wide user geography and a comprehensive approach to affiliate marketing.",
            descP: "Favorable offers and fair loyalty program",
            button: "Become a partner",
            what: "Why us?",
            card: "Top brand",
            cardDesc: "The world leader in the LootBox niche is caseblaze.com",
            card1: "Bro with you",
            card1Desc: "Support from our gang's personal manager",
            card2: "Flexible models",
            card2Desc: "Revenue Share from 20% Hybrid (CPA + RevShare)",
            card3: "Global chart",
            card3Desc: "We accept eSports traffic from all over the world",
            help: "We help you grow every day",
            earn: "and earn more",
            users: "Users",
            partners: "Partners",
            pay: "We pay partners daily",
            earning: "Start earning right now",
            invite: "We actively invite you to cooperate,",
            bloggers: "bloggers",
            and: "And",
            streamers: "streamers",
            write: "write to us right now !",
            contact: "Contact us",
        },
    },
    RU: {
        main: {
            what: "Что это такое?",
            desc: "Внимание! Кейсы выдаются согласно сумме депозитов. Сумма депозитов считается с 02:00 до 02:00 следующей ночи. Если вы не успели открыть бесплатный кейс до 02:00 - Прогресс сгорает.",
            pay: "Вы пополнили баланс на",
        },
        navElem: {
            users: "Игроков",
            cases: "Открыто кейсов",
            upgrade: "Апгрейдов",
            contracts: "Контрактов",
            online: "Онлайн",
        },
        header: {
            cases: "Кейсы",
            upgrade: "Апгрейды",
            contracts: "Контракты",
            deposit: "Депозит",
            bonuses: "Бонусы",
            wheel: "Барабан",
            knifeGame: "Угадай где нож",
        },
        subheader: {
            missions: "Миссии",
            calendar: "Календарь",
            cooperation: "Сотрудничество",
            referral: "Реферальная система",
            faq: "FAQ",
            freeCase: "Бесплатные кейс",
        },
        login: {
            title: "Авторизация",
            title1: "Я согласен с",
            title2: "Условием обслуживания",
            title3: "Политикой конфиденциальности",
            title4: "и соглашением держателем карты",
            subtitle: "Мне как минимум 18 лет",
            apply: "Подтверждаю",
        },
        profile: {
            profileTop: {
                deposit: "Пополнить",
                tradeUrl: "Трейд ссылка",
                howWork: "Как это работает?",
                promocode: "Промокод",
                promocodeText: "У вас есть промокод?",
                enterPromocode: "Введите промокод",
                bestCase: {
                    title: "Лучший кейс",
                    subtitle: "Отсутствует",
                    open: "Открыть кейс",
                },
                bestDrop: {
                    title: "Лучший дроп",
                    subtitle: "Отсутствует",
                },
            },
            profileBottom: {
                skins: "Предметы",
                upgrade: "Апгрейды",
                contracts: "Контракты",
                stock: "В наличии",
                sell: "Продать все",
            },
        },
        missions: {
            header: "Миссии",
        },
        calendar: {
            top: {
                text: "Открывай ячейки календаря ежедневно и получай награду! Каждый 10-ый день тебя ждет СУПЕРПРИЗ!",
                rules: "Правила календаря",
            },
            title: "Призы в календаре",
            bottom: {
                bonus: "Бонус на",
                balance: "баланс",
                key: "Ключ от",
                case: "кейса",
                random: "Рандомный",
                item: "Скин",
                promo: "Промокод",
            },
        },
        upgrade: {
            header: "Апгрейд",
            info: "Шанс на",
            chance: "успешный апгрейд",
            yourItems: "Инвентарь",
            siteItems: "Скины",
            price: "Цена",
            all: "Все",
            contraband: "Контрабанда",
            covert: "Тайное",
            classified: "Засекреченное",
            restricted: "Запрещенное",
            milspec: "Армейское",
            industrial: "Промышленное",
            consumer: "Consumer",
            price: "Цена",
        },
        deposit: {
            wallet: "Методы",
            title: "Депозит",
            method: "Выбранный метод",
            amount: "Сумма",
            promocode: "Промокод",
            order: "Пополнить",
            not_selected: "Не выбран",
        },
        trade: {
            url: "Трейд-ссылка",
            desc: "Трейд ссылка — это ссылка, которая дает вам возможность торговать с игроками, у которых вас нет в списке друзей.",
            link: "Ссылка",
            where: "Где взять?",
            enterLink: "Введите трейд-ссылку",
            apply: "Сохранить",
        },
        promocode: {
            title: "Промокод",
            desc: "Ищите коды в наших социальных сетях и рассылках, вводите в поле ниже и получайте деньги на баланс или кейсы.",
            apply: "Применить",
        },
        freecase: {
            header: "Бесплатные кейсы",
            title: "ОТКРЫВАЙТЕ БЕСПЛАТНЫЕ КЕЙСЫ CS2 КАЖДЫЙ ДЕНЬ",
            desc: "Чтобы открыть ежедневный кейс, вам нужно достичь нужного уровня, заработав XP. Чем выше ваш уровень, тем больше кейсов вам доступно. ",
            desc2: "Например, на 20 уровне вы сможете открывать по три кейса каждый день. Чтобы не забывать забирать ежедневный кейс каждый день, подпишитесь на уведомления. Мы напомним вам о не собранных кейсах",
            open: "ОТКРЫТЬ",
            lock: "НЕДОСТУПНО",
            free: "Бесплатно",
        },
        socialModals: {
            title: "ОДНОРАЗОВЫЙ БОНУС",
            desc: "Для получения Одноразового бонуса необходимо:",
            condition: "Подписаться на",
            important: "ВАЖНО:",
            desc2: "Скриншот должен быть полноэкранным и четким. Любая попытка обмана приведет к отказу от приза и блокировке задания без возможности обжалования.",
        },
        replaceItem: {
            title: "Замена скина",
            return: "Вернем на баланс",
            desc: "Выберите скин",
            replace: "Заменить",
            cancel: "Отменить",
        },
        raffleHour: {
            header: "Розыгрыши",
            title: "Каждый час",
            dep: "При пополнении от:",
            time: "Осталось времени",
            participate: "Участвовать",
            winners: "Последние победители",
            show: "Показать ещё",
            day: "Дней",
            hour: "Часов",
            min: "Минут",
            sec: "Секунд",
        },
        raffleDay: {
            title: "Каждый день",
        },
        raffleWeek: {
            title: "Каждую неделю",
        },
        bonuses: {
            title: "Подарки",
            ot: "от",
            text: "Вы с нами уже",
            text1: "день",
            text2: "спасибо что выбрали нас!",
            item: "Бонусные кейсы",
            itemDesc: "Открывай кейс ежемесячно!",
            item1: "Ежедневные бонусы",
            item1Desc: "Забирай награду каждый день!",
            bonus: "Разовые бонусы",
            subscribe: "Подписаться на",
            to: "наш",
            you_bonus: "Ваш бонус",
            take: "Забрать",
        },
        wheel: {
            title: "Барабан",
            subTitle: "Бонусов",
            hours: "Часов",
            minutes: "Минут",
            seconds: "Секунд",
            spin: "Крутим...",
            open: "Крутить",
            promo: "Ваш промокод (кликните, что бы скопировать):",
            use: "Использовать",
            refresh: "Крутить еще",
            what: "что может выпасть?",
            free: "До бесплатного",
            open1: "открытия осталось:",
        },
        knifeGame: {
            header: "Угадай где нож",
            balance: "Баланс",
            knivesCount: "Количество ножей",
            betAmount: "Сумма ставки",
            multiplier: "Множитель",
            startGame: "Начать игру",
            currentMultiplier: "Текущий множитель",
            potentialWin: "Потенциальный выигрыш",
            youWin: "Победа!",
            youLose: "Нож! Вы проиграли",
            history: "История игр",
            topWins: "Топ выигрышей",
            noHistory: "Игр пока нет",
            noTopWins: "Выигрышей пока нет",
            howToPlay: "Как играть?",
            howDesc1: "Выберите количество ножей (1, 2 или 3), введите ставку и нажмите «Начать игру».",
            howDesc2: "Нажимайте на ячейки, чтобы открывать их. Избегайте ножей! Каждая безопасная ячейка увеличивает множитель.",
            howDesc3: "Вы можете забрать выигрыш на 1/2, x2 или x3, или рискнуть ради максимального выигрыша.",
            loginRequired: "Войдите в аккаунт, чтобы играть",
        },
        referral: {
            title: "Реферальная система",
            silver: "Серебро",
            gold: "Золото",
            platinum: "Платина",
            promocode: "Промокод",
            create: "Создать",
            discount: "Скидка",
            percent: "Ваш процент",
            limit: "Лимит",
            total_deposit: "Пополнили на",
            gain: "Ваш заработок",
            dep: "При пополнении от",
            copy: "Скопировать",
        },
        contracts: {
            title: "Контракты",
            contract: "Контракт",
            create: "Создать контракт",
            add: "Добавьте минимум",
            item: "предмета",
            available: "Доступные для контракта предметы",
            happy: "Поздравляем!",
            refresh: "Начать снова",
            sell: "Продать за",
            warning: "Отсутствуют предметы для контракта!",
            warning2: "Откройте несколько кейсов",
            warning3:
                "вернитесь на эту страницу и Вы сможете создать контракт!",
        },
        faq: {
            title: "FAQ",
            item: "Пополнил баланс, а деньги не пришли на счёт. Что делать?",
            desc: "Если денежные средства не пришли сразу после пополнения, не переживайте. Подождите 1 час. Если в течение часа деньги не поступили, обратитесь, пожалуйста, в поддержку, указав подробные данные платежа.",
            item1: "После открытия кейса, вещь не пришла либо вы не можете ее забрать. Что необходимо сделать?",
            desc1: "Если вещь не пришла, зайдите в свой профиль и кликните по ссылке “Забрать” на интересующем вас предмете. Если же вещь не выводится, возможно дело в том, что: у вас заблокирован обмен, скрыт инвентарь, у бота возникли проблемы со связью Steam. Напишите, пожалуйста, в нашу поддержку и мы максимально быстро найдем причину и решим ее.",
            item2: "У меня есть деньги на Steam аккаунте, но на caseblaze они не отображаются. Почему?",
            desc2: "К сожалению, баланс Steam не действует на caseblaze.com Но вы всегда можете пополнить баланс отдельно, через кнопку “Пополнить баланс”",
            item3: "Почему я не могу применить промокод?",
            desc3: "Некоторые промокоды возможно использовать только при определенном уровне Steam аккаунта. К сожалению, вы не сможете воспользоваться промокодом с 0 уровнем Steam аккаунта.",
            item4: "Я не нашел интересующего меня вопроса.",
            desc4: "Не расстраивайтесь. Вы всегда можете написать нам в поддержку и мы максимально быстро ответим на ваш вопрос.",
        },
        cases: {
            content: "Содержимое кейса",
            sign: "Войти!",
            warning: "Для открытия кейсов требуется авторизация Steam.",
            enough: "не хватает",
            deposit: "Пополнить",
            open: "Открыть за",
            free: {
                title: "ДЛЯ ОТКРЫТИЯ КЕЙСА ВАМ НЕОБХОДИМО",
                text: "Пополнить баланс за последние 24 часа не менее, чем на",
                text1: "За последние 24 часа вы пополнили баланс на",
                text2: "Важно! Успейте открыть до 02:00,",
                text3: "в противном случае прогресс пополнений будет обнулен",
            },
            return: "ещё раз",
            sell: "Продать за",
            sellAll: "Продать все за",
            upgrade: "в апгрейд",
        },
        contacts: {
            help: "Нужна помощь?",
            questions:
                "Для любых вопросов и предложений напишите нам на почтовый ящик — ",
        },
        cooperation: {
            name: "Сотрудничество",
            title: "Прокачай доход с caseblaze — прямым рекламодателем гемблинг-продукта",
            desc: "Высокая конверсия, обширная география пользователей и комплексный подход к партнерскому маркетингу.",
            descP: "Выгодные офферы и справедливая программа лояльности",
            button: "Стать партнером",
            what: "Почему мы?",
            card: "Топовый бренд",
            cardDesc: "Мировой лидер в нише LootBox — caseblaze",
            card1: "Бро с тобой",
            card1Desc: "Поддержка от личного менеджера нашей банды",
            card2: "Гибкие модели",
            card2Desc: "Revenue Share от 20% Гибрид (CPA + RevShare)",
            card3: "Глобальный график",
            card3Desc: "Принимаем киберспортивный трафик со всего мира",
            help: "Помогаем расти каждый день",
            earn: "и зарабатывать большe",
            users: "Пользователей",
            partners: "Партнеров",
            pay: "Ежедневно выплачиваем партнерам",
            earning: "Начни зарабатывать прямо сейчас",
            invite: "Мы активно приглашаем к сотрудничеству,",
            bloggers: "блогеров",
            and: "и",
            streamers: "стримеров",
            write: "напиши нам прямо сейчас !",
            contact: "Связаться с нами",
        },
    },
};
